# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 23:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0004_visita'),
        ('donante', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donante',
            name='escuela',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='escuela.Escuela'),
        ),
    ]
