# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-28 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donante', '0002_donante_escuela'),
    ]

    operations = [
        migrations.AddField(
            model_name='donante',
            name='donacion',
            field=models.FloatField(default=0),
        ),
    ]
