# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0002_persona_grado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='grado',
            field=models.CharField(blank=True, choices=[('K', 'Preescolar'), ('1', '1-Primer'), ('2', '2-Segundo'), ('3', '3-Tercer'), ('4', '4-Cuarto'), ('5', '5-Quinto'), ('6', '6-Sexto'), ('D', 'Docente'), ('P', 'Director'), ('V', 'Voluntario')], max_length=1),
        ),
    ]
