# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0003_auto_20170513_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('fecha', models.DateField()),
                ('tipo_visita', models.CharField(choices=[('1', 'Educativa'), ('2', 'Tecnico'), ('3', 'Logistico')], max_length=1)),
                ('objetivo', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=250)),
                ('avances', models.CharField(max_length=100)),
                ('escuela', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='escuela.Escuela')),
            ],
        ),
    ]
