# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=11)),
                ('uuid', models.CharField(max_length=32)),
                ('modelo', models.CharField(choices=[('1', 'XO1'), ('2', 'XO1.5'), ('3', 'XO1.75'), ('4', 'XO4'), ('5', 'NL3')], max_length=1)),
            ],
            options={
                'ordering': ('serie',),
            },
        ),
    ]
