# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0002_incidente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='incidente',
            name='fecha',
        ),
        migrations.AddField(
            model_name='incidente',
            name='laptop',
            field=models.ManyToManyField(blank=True, to='laptop.Laptop'),
        ),
        migrations.AddField(
            model_name='incidente',
            name='componente',
            field=models.ManyToManyField(blank=True, to='laptop.Componente'),
        ),
    ]
