# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 16:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0004_auto_20170513_2221'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laptop',
            options={'ordering': ('id',)},
        ),
    ]
