# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-05 18:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0005_auto_20170520_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidente',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
